// Font Awesome-konfiguration för hellonoid.com
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faRobot,
  faBolt,
  faBatteryHalf,
  faBatteryFull,
  faTag,
  faShirt,
  faBroom,
  faStairs,
  faMicrophone,
  faMicrophoneSlash,
  faGamepad,
  faDumbbell,
  faBox,
  faRulerCombined,
  faEye,
  faHandFist,
  faClipboardList,
  // Admin icons
  faGauge,
  faNewspaper,
  faPlus,
  faPenToSquare,
  faTrash,
  faClock,
  faUser,
  faEnvelope,
  faShieldHalved,
  faCalendarDay,
  faLink,
  faArrowUpRightFromSquare,
  faGlobe,
  faBuilding,
  faImage,
  faFloppyDisk,
  faXmark,
  faChevronLeft,
  faChevronRight,
  faMagnifyingGlass,
  faFilter,
  faCircleInfo,
  faTriangleExclamation,
  faCheck,
  faSpinner,
} from '@fortawesome/free-solid-svg-icons';

// Lägg till alla ikoner som behövs i biblioteket
library.add(
  faRobot, faBolt, faBatteryHalf, faBatteryFull, faTag, faShirt, faBroom,
  faStairs, faMicrophone, faMicrophoneSlash, faGamepad, faDumbbell, faBox,
  faRulerCombined, faEye, faHandFist, faClipboardList,
  faGauge, faNewspaper, faPlus, faPenToSquare, faTrash, faClock, faUser,
  faEnvelope, faShieldHalved, faCalendarDay, faLink, faArrowUpRightFromSquare,
  faGlobe, faBuilding, faImage, faFloppyDisk, faXmark, faChevronLeft,
  faChevronRight, faMagnifyingGlass, faFilter, faCircleInfo, faTriangleExclamation,
  faCheck, faSpinner,
);

export {
  faRobot, faBolt, faBatteryHalf, faBatteryFull, faTag, faShirt, faBroom,
  faStairs, faMicrophone, faMicrophoneSlash, faGamepad, faDumbbell, faBox,
  faRulerCombined, faEye, faHandFist, faClipboardList,
  faGauge, faNewspaper, faPlus, faPenToSquare, faTrash, faClock, faUser,
  faEnvelope, faShieldHalved, faCalendarDay, faLink, faArrowUpRightFromSquare,
  faGlobe, faBuilding, faImage, faFloppyDisk, faXmark, faChevronLeft,
  faChevronRight, faMagnifyingGlass, faFilter, faCircleInfo, faTriangleExclamation,
  faCheck, faSpinner,
};
